//@version=6
import DevLucem/ZigLib/1 as ZigZag
indicator('ZigZag++SAI', 'ZigZag++ [SAI]', true, format.price, max_labels_count = 200, max_lines_count = 50)

////////
// Fetch Ingredients 
// [
Depth = input.int(15, 'Depth', minval=1, step=1, group="ZigZag Config")
Deviation = input.int(5, 'Deviation', minval=1, step=1, group="ZigZag Config")
Backstep = input.int(10, 'Backstep', minval=2, step=1, group="ZigZag Config")
line_thick = input.int(3, 'Line Thickness', minval=1, maxval=4, group="Lines")
labels = input(0, 'Labels Transparency', group = 'Labels')
upcolor = input(color.lime, 'Bull Color', group = 'Colors')
dncolor = input(color.red, 'Bear Color', group = 'Colors')
lines = input(0, 'Lines Transparency', group = 'Lines')
background = input(80, 'Background Transparency', group = 'Colors')
label_size__0 = input.int(3, 'Label SIze', minval = 1, maxval = 5, group = 'Labels')
label_size = switch label_size__0
    1 => size.tiny
    2 => size.small
    3 => size.normal
    4 => size.large
    5 => size.huge
repaint = input(true, 'Repaint Levels')
extend = input(false, 'Extend ZigZag', group = 'Lines')
// ]


// ////////
// // Bake it with a simple oven this time
[direction, z1, z2] = ZigZag.zigzag(low, high, Depth, Deviation, Backstep)
string nowPoint = ''
field_0 = z1.price
var float lastPoint = field_0[1]
if bool(ta.change(direction))
    field_1 = z1.price
    lastPoint := field_1[1]
    lastPoint


// ////////
// // Let it Cool And Serve
line zz = na
label point = na

if repaint
    zz := line.new(z1, z2, xloc.bar_time, extend ? extend.right : extend.none, color.new(direction > 0 ? upcolor : dncolor, lines), width = line_thick)
    nowPoint := direction < 0 ? z2.price < lastPoint ? 'LL' : 'HL' : z2.price > lastPoint ? 'HH' : 'LH'
    point := label.new(z2, nowPoint, xloc.bar_time, yloc.price, color.new(direction < 0 ? upcolor : dncolor, labels), direction > 0 ? label.style_label_down : label.style_label_up, color.new(direction > 0 ? upcolor : dncolor, labels), label_size)
    if direction == direction[1]
        line.delete(zz[1])
        label.delete(point[1])
    else
        line.set_extend(zz[1], extend.none)
else
    if direction != direction[1]
        zz := line.new(z1[1], z2[1], xloc.bar_time, extend.none, color.new(direction > 0 ? upcolor : dncolor, lines), width = line_thick)
        field_2 = z2.price
        field_3 = z2.price
        nowPoint := direction[1] < 0 ? field_2[1] < lastPoint[1] ? 'LL' : 'HL' : field_3[1] > lastPoint[1] ? 'HH' : 'LH'
        point := label.new(z2[1], nowPoint, xloc.bar_time, yloc.price, color.new(direction[1] < 0 ? upcolor : dncolor, labels), direction[1] > 0 ? label.style_label_down : label.style_label_up, color.new(direction[1] > 0 ? upcolor : dncolor, labels), label_size)
        point
bgcolor(direction < 0 ? color.new(dncolor, background) : color.new(upcolor, background), title = 'Direction Background')
plotarrow(direction, 'direction', display = display.status_line)


// ////////
// // Declare Meal Was Sweet By Force
field_4 = z2.price
alertcondition(nowPoint == 'HH' and z2.price != field_4[1], 'New Higher High', 'Zigzag on {{ticker}} higher higher high detected at {{time}}')
field_5 = z2.price
alertcondition(nowPoint == 'LH' and z2.price != field_5[1], 'New Lower High', 'Zigzag on {{ticker}} higher lower high detected at {{time}}')
field_6 = z2.price
alertcondition(nowPoint == 'HL' and z2.price != field_6[1], 'New Higher Low', 'Zigzag on {{ticker}} higher lower low detected at {{time}}')
field_7 = z2.price
alertcondition(nowPoint == 'LL' and z2.price != field_7[1], 'New Lower Low', 'Zigzag on {{ticker}} lower low detected at {{time}}')
alertcondition(direction != direction[1], 'Direction Changed', 'Zigzag on {{ticker}} direction changed at {{time}}')
alertcondition(direction != direction[1] and direction > 0, 'Bullish Direction', 'Zigzag on {{ticker}} bullish direction at {{time}}')
alertcondition(direction != direction[1] and direction < 0, 'Bearish Direction', 'Zigzag on {{ticker}} bearish direction at {{time}}')

if direction != direction[1]
    alert((direction < 0 ? 'Bearish' : 'Bullish') + ' Direction Final ', alert.freq_once_per_bar_close)
